// <auto-generated />
using System;
using FatouraDZ.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FatouraDZ.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260923234815_ClientLinkOnFacture")]
    partial class ClientLinkOnFacture
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("FatouraDZ.Models.Business", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Activite")
                        .HasColumnType("TEXT");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CapitalSocial")
                        .HasColumnType("TEXT");

                    b.Property<string>("CheminLogo")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodePostal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fax")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NIF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NIS")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroImmatriculation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RaisonSociale")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeEntreprise")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Wilaya")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Businesses");
                });

            modelBuilder.Entity("FatouraDZ.Models.CategorieTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("CategoriesTransaction");
                });

            modelBuilder.Entity("FatouraDZ.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AI")
                        .HasColumnType("TEXT");

                    b.Property<string>("Activite")
                        .HasColumnType("TEXT");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CapitalSocial")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fax")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormeJuridique")
                        .HasColumnType("TEXT");

                    b.Property<string>("NIF")
                        .HasColumnType("TEXT");

                    b.Property<string>("NIS")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroImmatriculation")
                        .HasColumnType("TEXT");

                    b.Property<string>("RC")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeClient")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("FatouraDZ.Models.Configuration", b =>
                {
                    b.Property<string>("Cle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Valeur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Cle");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("FatouraDZ.Models.Facture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CheminPDF")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientAI")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientActivite")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientAdresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientBusinessType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientCapitalSocial")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientFax")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientFormeJuridique")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientNIF")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientNIS")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientNom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientNumeroImmatriculation")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientRC")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientTelephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateEcheance")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateFacture")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateValidite")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstTimbreApplique")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModePaiement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MontantEnLettres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantRemiseGlobale")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroFacture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroFactureOrigine")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaiementNumeroPiece")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaiementReference")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PaiementValeur")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RemiseGlobale")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RetenueSource")
                        .HasColumnType("TEXT");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TauxRetenueSource")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TimbreFiscal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalHT")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalTTC")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalTVA19")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalTVA9")
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeFacture")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeRemiseGlobale")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("ClientId");

                    b.HasIndex("NumeroFacture")
                        .IsUnique();

                    b.ToTable("Factures");
                });

            modelBuilder.Entity("FatouraDZ.Models.LigneFacture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FactureId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontantRemise")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroLigne")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantite")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Remise")
                        .HasColumnType("TEXT");

                    b.Property<int>("TauxTVA")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalHT")
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeRemise")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Unite")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FactureId");

                    b.ToTable("LignesFacture");
                });

            modelBuilder.Entity("FatouraDZ.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FactureId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Montant")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroFacture")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FatouraDZ.Models.CategorieTransaction", b =>
                {
                    b.HasOne("FatouraDZ.Models.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("FatouraDZ.Models.Client", b =>
                {
                    b.HasOne("FatouraDZ.Models.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("FatouraDZ.Models.Facture", b =>
                {
                    b.HasOne("FatouraDZ.Models.Business", "Business")
                        .WithMany("Factures")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FatouraDZ.Models.Client", "Client")
                        .WithMany("Factures")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Business");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("FatouraDZ.Models.LigneFacture", b =>
                {
                    b.HasOne("FatouraDZ.Models.Facture", "Facture")
                        .WithMany("Lignes")
                        .HasForeignKey("FactureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facture");
                });

            modelBuilder.Entity("FatouraDZ.Models.Transaction", b =>
                {
                    b.HasOne("FatouraDZ.Models.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("FatouraDZ.Models.Business", b =>
                {
                    b.Navigation("Factures");
                });

            modelBuilder.Entity("FatouraDZ.Models.Client", b =>
                {
                    b.Navigation("Factures");
                });

            modelBuilder.Entity("FatouraDZ.Models.Facture", b =>
                {
                    b.Navigation("Lignes");
                });
#pragma warning restore 612, 618
        }
    }
}
